"""Write deployment-specific SEO files without embedding a hostname in source."""

import argparse
import json
from pathlib import Path
from urllib.parse import urlsplit
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SITEMAP = "http://www.sitemaps.org/schemas/sitemap/0.9"
XHTML = "http://www.w3.org/1999/xhtml"


def normalize_origin(value):
    parsed = urlsplit(value.strip())
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path not in ("", "/")
        or parsed.query
        or parsed.fragment
        or any(character.isspace() for character in value)
    ):
        raise ValueError("Expected an HTTPS origin without credentials, path, query or fragment.")
    return f"https://{parsed.netloc}"


def sitemap_document(origin, pages):
    origin = normalize_origin(origin)
    ET.register_namespace("", SITEMAP)
    ET.register_namespace("xhtml", XHTML)
    root = ET.Element(f"{{{SITEMAP}}}urlset")
    for view, page in pages.items():
        if view in {"dashboard", "not-found"}:
            continue
        urls = {"pt-BR": origin + page["path"], "en": origin + "/en" + page["path"]}
        for url in urls.values():
            entry = ET.SubElement(root, f"{{{SITEMAP}}}url")
            ET.SubElement(entry, f"{{{SITEMAP}}}loc").text = url
            for lang, alternate in {**urls, "x-default": urls["pt-BR"]}.items():
                ET.SubElement(entry, f"{{{XHTML}}}link", rel="alternate", hreflang=lang, href=alternate)
    ET.indent(root, space="  ")
    return ET.tostring(root, encoding="utf-8", xml_declaration=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--origin", required=True)
    args = parser.parse_args()
    origin = normalize_origin(args.origin)
    pages = json.loads((ROOT / "apps/web-src/pages.json").read_text(encoding="utf-8"))
    output = ROOT / "apps/web"
    (output / "sitemap.xml").write_bytes(sitemap_document(origin, pages))
    (output / "robots.txt").write_text(
        "# Generated by scripts/write_sitemap.py\nUser-agent: *\nAllow: /\nDisallow: /api/\n\nSitemap: "
        + origin + "/sitemap.xml\n", encoding="utf-8", newline="\n",
    )
    print("Generated sitemap.xml and robots.txt for the deployment origin.")


if __name__ == "__main__":
    main()
